### ISSUE TITLE
No module found

### ISSUE THREAD

**Issue by FotisSp** [alup/python_greek_stemmer#1]
After installing using `python setup.py install`  when i try to run your tests i get the following error : 

> Traceback (most recent call last):
  File "test_stemmer.py", line 5, in <module>
    from greek_stemmer import GreekStemmer
ImportError: No module named greek_stemmer

any suggestions ?

**Comment by alup** [comment]
How did you run the tests? Can you provide more details? E.g. python version etc.

You should run tests by using something like `python -m pytest tests/`.

**Comment by alup** [comment]
I have also updated the README. Feel free to check the installation instructions.

**Comment by FotisSp** [comment]
my python version is 2.7.12 and the way i tested it was sby creating a simple py file with the line
`from greek_stemmer import GreekStemmer` it says that couldn't find any module named greek_stemmer.

Also i couldn't find the requirements.txt file where can i find that ?

**Comment by alup** [comment]
Sorry for the inconvenience ... I have fixed some issues and uploaded a new 0.1.1 version to PyPI. Can you try with the new version? It should be ok.

As far as the test requirements, I have chosen not to include the tests folder in the release. So, if you want to run the tests you must clone the repository, install pytest (via the requirements file which I just checked-in) and run with the above command.

**Comment by FotisSp** [comment]
Okay now it seems to pass the compilation phase but my problem now is that if i give as input a word it returns to me the same word. For example i tried the word `'ΘΑΛΑΣΣΑ'` .

**Comment by alup** [comment]
Did you use a unicode type string? E.g.

```
>>> from greek_stemmer import GreekStemmer
>>> stemmer = GreekStemmer()
>>> stemmer.stem(u'ΘΑΛΑΣΣΑ')
ΘΑΛΑΣΣ
```

In python 2.7 you should explicitly use `u` for unicode strings.

**Comment by FotisSp** [comment]
Okay that fixed the problem ! Thank you

**Comment by alup** [comment]
Glad that I have finally helped you!
